### PR TITLE
build: update ci

### PR DESCRIPTION
**Pull request by janniks**
> in preparation for `buffer` removal

- updates CI (similar to previous https://github.com/stacks-network/jsontokens-js/pull/64)
  - adds auto-release pipeline
  - moves tests from CircleCI to GitHub Actions
- auto-formats with updated rules (no logic changes)

### CODE REVIEW

**Comment by janniks** [comment]
@blockstack-devops @CharlieC3 Can you add the same ENV variables to GitHub Actions, which the https://github.com/stacks-network/jsontokens-js repo also has. (ie `NPM_TOKEN`, `GITHUB_TOKEN`)

**Comment by CharlieC3** [comment]
@janniks Those are org-level secrets, so they're available in each repo!

**Comment by janniks** [comment]
> @janniks Those are org-level secrets, so they're available in each repo!

Ahaa — perfect 😎 thanks

**Review by CharlieC3 — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
